# Generated by Django 5.1.2 on 2024-11-16 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='bio',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='location',
            new_name='phone',
        ),
    ]
