# Generated by Django 5.1.2 on 2024-11-04 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks_app', '0004_remove_task_sub_tasks_task_sub_tasks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='assigned',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='task',
            name='category',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='task',
            name='due_date',
            field=models.DateField(blank=True, default='1.1.1999', null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='priority_content',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='task',
            name='sub_tasks',
            field=models.ManyToManyField(blank=True, default='', to='tasks_app.subtask'),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_status',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='task',
            name='title',
            field=models.CharField(default='', max_length=255),
        ),
    ]
