# Generated by Django 5.1.2 on 2024-11-04 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks_app', '0007_alter_task_assigned_alter_task_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='sub_tasks',
        ),
        migrations.AddField(
            model_name='task',
            name='sub_tasks',
            field=models.JSONField(default=list),
        ),
    ]
