# Generated by Django 5.1.2 on 2024-11-04 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks_app', '0008_remove_task_sub_tasks_task_sub_tasks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='category',
            field=models.JSONField(default=list),
        ),
    ]
