# Generated by Django 5.1.2 on 2024-11-05 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks_app', '0010_usercontact_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercontact',
            name='email',
            field=models.CharField(max_length=255),
        ),
    ]
