# Generated by Django 5.1.2 on 2024-11-05 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks_app', '0011_alter_usercontact_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercontact',
            name='email',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='usercontact',
            name='name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='usercontact',
            name='phone',
            field=models.CharField(default='', max_length=15),
        ),
    ]
