# Generated by Django 5.1.2 on 2024-11-09 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks_app', '0012_alter_usercontact_email_alter_usercontact_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subtask',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='task',
            name='due_date',
            field=models.DateField(blank=True, default='1999-01-01', null=True),
        ),
        migrations.RemoveField(
            model_name='task',
            name='sub_tasks',
        ),
        migrations.AddField(
            model_name='task',
            name='sub_tasks',
            field=models.ManyToManyField(blank=True, related_name='tasks', to='tasks_app.subtask'),
        ),
    ]
