# Generated by Django 5.1.2 on 2024-11-17 16:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks_app', '0015_remove_task_user_task_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='due_date',
            field=models.DateField(blank=True, default=datetime.date(1999, 1, 1), null=True),
        ),
    ]
