# Generated by Django 5.1.2 on 2024-11-18 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts_app', '0005_alter_usercontact_email_alter_usercontact_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercontact',
            name='phone',
            field=models.CharField(default=None, max_length=15),
        ),
    ]
