# Generated by Django 5.1.2 on 2024-11-18 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts_app', '0006_alter_usercontact_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercontact',
            name='phone',
            field=models.CharField(default='', max_length=30),
        ),
    ]
